using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SAPB1.Sap_Objects
{
    public class BusinessPartners
    {
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string CardType { get; set; }
        public int GroupCode { get; set; }
        public object Address { get; set; }
        public object ZipCode { get; set; }
        public object MailAddress { get; set; }
        public object MailZipCode { get; set; }
        public object Phone1 { get; set; }
        public object Phone2 { get; set; }
        public object Fax { get; set; }
        public object ContactPerson { get; set; }
        public object Notes { get; set; }
        public int PayTermsGrpCode { get; set; }
        public double CreditLimit { get; set; }
        public double MaxCommitment { get; set; }
        public double DiscountPercent { get; set; }
        public string VatLiable { get; set; }
        public string FederalTaxID { get; set; }
        public string DeductibleAtSource { get; set; }
        public double DeductionPercent { get; set; }
        public object DeductionValidUntil { get; set; }
        public int PriceListNum { get; set; }
        public double IntrestRatePercent { get; set; }
        public double CommissionPercent { get; set; }
        public int CommissionGroupCode { get; set; }
        public object FreeText { get; set; }
        public int SalesPersonCode { get; set; }
        public string Currency { get; set; }
        public string RateDiffAccount { get; set; }
        public object Cellular { get; set; }
        public object AvarageLate { get; set; }
        public object City { get; set; }
        public object County { get; set; }
        public string Country { get; set; }
        public object MailCity { get; set; }
        public object MailCounty { get; set; }
        public string MailCountry { get; set; }
        public object EmailAddress { get; set; }
        public object Picture { get; set; }
        public object DefaultAccount { get; set; }
        public object DefaultBranch { get; set; }
        public string DefaultBankCode { get; set; }
        public object AdditionalID { get; set; }
        public object Pager { get; set; }
        public object FatherCard { get; set; }
        public object CardForeignName { get; set; }
        public string FatherType { get; set; }
        public object DeductionOffice { get; set; }
        public object ExportCode { get; set; }
        public double MinIntrest { get; set; }
        public double CurrentAccountBalance { get; set; }
        public double OpenDeliveryNotesBalance { get; set; }
        public double OpenOrdersBalance { get; set; }
        public object VatGroup { get; set; }
        public object ShippingType { get; set; }
        public object Password { get; set; }
        public object Indicator { get; set; }
        public object IBAN { get; set; }
        public int CreditCardCode { get; set; }
        public string CreditCardNum { get; set; }
        public object CreditCardExpiration { get; set; }
        public string DebitorAccount { get; set; }
        public object OpenOpportunities { get; set; }
        public string Valid { get; set; }
        public object ValidFrom { get; set; }
        public object ValidTo { get; set; }
        public object ValidRemarks { get; set; }
        public string Frozen { get; set; }
        public object FrozenFrom { get; set; }
        public object FrozenTo { get; set; }
        public object FrozenRemarks { get; set; }
        public object Block { get; set; }
        public object BillToState { get; set; }
        public object ExemptNum { get; set; }
        public int Priority { get; set; }
        public object FormCode1099 { get; set; }
        public object Box1099 { get; set; }
        public object PeymentMethodCode { get; set; }
        public string BackOrder { get; set; }
        public string PartialDelivery { get; set; }
        public string BlockDunning { get; set; }
        public object BankCountry { get; set; }
        public string HouseBank { get; set; }
        public string HouseBankCountry { get; set; }
        public string HouseBankAccount { get; set; }
        public object ShipToDefault { get; set; }
        public int DunningLevel { get; set; }
        public object DunningDate { get; set; }
        public string CollectionAuthorization { get; set; }
        public object DME { get; set; }
        public object InstructionKey { get; set; }
        public string SinglePayment { get; set; }
        public object ISRBillerID { get; set; }
        public string PaymentBlock { get; set; }
        public object ReferenceDetails { get; set; }
        public string HouseBankBranch { get; set; }
        public object OwnerIDNumber { get; set; }
        public int PaymentBlockDescription { get; set; }
        public object TaxExemptionLetterNum { get; set; }
        public double MaxAmountOfExemption { get; set; }
        public object ExemptionValidityDateFrom { get; set; }
        public object ExemptionValidityDateTo { get; set; }
        public object LinkedBusinessPartner { get; set; }
        public object LastMultiReconciliationNum { get; set; }
        public string DeferredTax { get; set; }
        public string Equalization { get; set; }
        public string SubjectToWithholdingTax { get; set; }
        public string CertificateNumber { get; set; }
        public object ExpirationDate { get; set; }
        public string NationalInsuranceNum { get; set; }
        public string AccrualCriteria { get; set; }
        public string WTCode { get; set; }
        public object BillToBuildingFloorRoom { get; set; }
        public object DownPaymentClearAct { get; set; }
        public object ChannelBP { get; set; }
        public object DefaultTechnician { get; set; }
        public object BilltoDefault { get; set; }
        public object CustomerBillofExchangDisc { get; set; }
        public object Territory { get; set; }
        public object ShipToBuildingFloorRoom { get; set; }
        public object CustomerBillofExchangPres { get; set; }
        public object ProjectCode { get; set; }
        public object VatGroupLatinAmerica { get; set; }
        public object DunningTerm { get; set; }
        public object Website { get; set; }
        public object OtherReceivablePayable { get; set; }
        public object BillofExchangeonCollection { get; set; }
        public string CompanyPrivate { get; set; }
        public int LanguageCode { get; set; }
        public object UnpaidBillofExchange { get; set; }
        public int WithholdingTaxDeductionGroup { get; set; }
        public object ClosingDateProcedureNumber { get; set; }
        public object Profession { get; set; }
        public object BankChargesAllocationCode { get; set; }
        public string TaxRoundingRule { get; set; }
        public string Properties1 { get; set; }
        public string Properties2 { get; set; }
        public string Properties3 { get; set; }
        public string Properties4 { get; set; }
        public string Properties5 { get; set; }
        public string Properties6 { get; set; }
        public string Properties7 { get; set; }
        public string Properties8 { get; set; }
        public string Properties9 { get; set; }
        public string Properties10 { get; set; }
        public string Properties11 { get; set; }
        public string Properties12 { get; set; }
        public string Properties13 { get; set; }
        public string Properties14 { get; set; }
        public string Properties15 { get; set; }
        public string Properties16 { get; set; }
        public string Properties17 { get; set; }
        public string Properties18 { get; set; }
        public string Properties19 { get; set; }
        public string Properties20 { get; set; }
        public string Properties21 { get; set; }
        public string Properties22 { get; set; }
        public string Properties23 { get; set; }
        public string Properties24 { get; set; }
        public string Properties25 { get; set; }
        public string Properties26 { get; set; }
        public string Properties27 { get; set; }
        public string Properties28 { get; set; }
        public string Properties29 { get; set; }
        public string Properties30 { get; set; }
        public string Properties31 { get; set; }
        public string Properties32 { get; set; }
        public string Properties33 { get; set; }
        public string Properties34 { get; set; }
        public string Properties35 { get; set; }
        public string Properties36 { get; set; }
        public string Properties37 { get; set; }
        public string Properties38 { get; set; }
        public string Properties39 { get; set; }
        public string Properties40 { get; set; }
        public string Properties41 { get; set; }
        public string Properties42 { get; set; }
        public string Properties43 { get; set; }
        public string Properties44 { get; set; }
        public string Properties45 { get; set; }
        public string Properties46 { get; set; }
        public string Properties47 { get; set; }
        public string Properties48 { get; set; }
        public string Properties49 { get; set; }
        public string Properties50 { get; set; }
        public string Properties51 { get; set; }
        public string Properties52 { get; set; }
        public string Properties53 { get; set; }
        public string Properties54 { get; set; }
        public string Properties55 { get; set; }
        public string Properties56 { get; set; }
        public string Properties57 { get; set; }
        public string Properties58 { get; set; }
        public string Properties59 { get; set; }
        public string Properties60 { get; set; }
        public string Properties61 { get; set; }
        public string Properties62 { get; set; }
        public string Properties63 { get; set; }
        public string Properties64 { get; set; }
        public object CompanyRegistrationNumber { get; set; }
        public object VerificationNumber { get; set; }
        public string DiscountBaseObject { get; set; }
        public string DiscountRelations { get; set; }
        public string TypeReport { get; set; }
        public string ThresholdOverlook { get; set; }
        public string SurchargeOverlook { get; set; }
        public object DownPaymentInterimAccount { get; set; }
        public string OperationCode347 { get; set; }
        public string InsuranceOperation347 { get; set; }
        public string HierarchicalDeduction { get; set; }
        public string ShaamGroup { get; set; }
        public string WithholdingTaxCertified { get; set; }
        public string BookkeepingCertified { get; set; }
        public object PlanningGroup { get; set; }
        public string Affiliate { get; set; }
        public object Industry { get; set; }
        public object VatIDNum { get; set; }
        public object DatevAccount { get; set; }
        public string DatevFirstDataEntry { get; set; }
        public object GTSRegNo { get; set; }
        public object GTSBankAccountNo { get; set; }
        public object GTSBillingAddrTel { get; set; }
        public object ETaxWebSite { get; set; }
        public string HouseBankIBAN { get; set; }
        public object VATRegistrationNumber { get; set; }
        public object RepresentativeName { get; set; }
        public object IndustryType { get; set; }
        public object BusinessType { get; set; }
        public int Series { get; set; }
        public object AutomaticPosting { get; set; }
        public object InterestAccount { get; set; }
        public object FeeAccount { get; set; }
        public object CampaignNumber { get; set; }
        public object AliasName { get; set; }
        public object DefaultBlanketAgreementNumber { get; set; }
        public string EffectiveDiscount { get; set; }
        public string NoDiscounts { get; set; }
        public object GlobalLocationNumber { get; set; }
        public object EDISenderID { get; set; }
        public object EDIRecipientID { get; set; }
        public string ResidenNumber { get; set; }
        public object RelationshipCode { get; set; }
        public object RelationshipDateFrom { get; set; }
        public object RelationshipDateTill { get; set; }
        public object UnifiedFederalTaxID { get; set; }
        public object AttachmentEntry { get; set; }
        public object TypeOfOperation { get; set; }
        public string EndorsableChecksFromBP { get; set; }
        public string AcceptsEndorsedChecks { get; set; }
        public object OwnerCode { get; set; }
        public string BlockSendingMarketingContent { get; set; }
        public object AgentCode { get; set; }
        public object EDocGenerationType { get; set; }
        public object EDocStreet { get; set; }
        public object EDocStreetNumber { get; set; }
        public object EDocBuildingNumber { get; set; }
        public object EDocZipCode { get; set; }
        public object EDocCity { get; set; }
        public object EDocCountry { get; set; }
        public object EDocDistrict { get; set; }
        public object EDocRepresentativeFirstName { get; set; }
        public object EDocRepresentativeSurname { get; set; }
        public object EDocRepresentativeCompany { get; set; }
        public object EDocRepresentativeFiscalCode { get; set; }
        public object EDocRepresentativeAdditionalId { get; set; }
        public object EDocPECAddress { get; set; }
        public object IPACodeForPA { get; set; }
        public string UpdateDate { get; set; }
        public string UpdateTime { get; set; }
        public string ExemptionMaxAmountValidationType { get; set; }
        public object ECommerceMerchantID { get; set; }
        public string UseBillToAddrToDetermineTax { get; set; }
        public object U_critico { get; set; }
        public object U_eva_inicial { get; set; }
        public double U_patrimonio { get; set; }
        public double U_cuota_mensual { get; set; }
        public double U_cuotas_activar { get; set; }
        public string U_afi_verificador { get; set; }
        public object U_actividad { get; set; }
        public string U_cobrador { get; set; }
        public object U_primera_afiliacion { get; set; }
        public object U_primera_desafiliacion { get; set; }
        public object U_segunda_afiliacion { get; set; }
        public object U_segunda_desafiliacion { get; set; }
        public object U_tercera_afiliacion { get; set; }
        public object U_tercera_desafiliacion { get; set; }
        public object U_cuarta_afiliacion { get; set; }
        public object U_cuarta_desafiliacion { get; set; }
        public object U_quinta_afiliacion { get; set; }
        public object U_quinta_desafiliacion { get; set; }
        public object U_estado_matricula { get; set; }
        public object U_nro_matricula { get; set; }
        public object U_fecha_matricula { get; set; }
        public object U_gestion_matricula { get; set; }
        public object U_estado_nit { get; set; }
        public object U_regimen_nit { get; set; }
        public object U_sucursal_nit { get; set; }
        public object U_tipo_nit { get; set; }
        public object U_estado_padron { get; set; }
        public object U_nro_padron { get; set; }
        public object U_departamento_padron { get; set; }
        public object U_municipio_padron { get; set; }
        public object U_fechaemision_padron { get; set; }
        public object U_estado_balance { get; set; }
        public object U_asamblea_balance { get; set; }
        public object U_ultimo_balance { get; set; }
        public double U_montoultimo_balance { get; set; }
        public object U_visado_balance { get; set; }
        public double U_montovisado_balance { get; set; }
        public object U_ventasanulaes_balance { get; set; }
        public object U_cod_antiguo { get; set; }
        public object U_nro_nit { get; set; }
        public string U_tipo { get; set; }
        public object U_empresa { get; set; }
        public double U_SBO_PORCENTAJE { get; set; }
        public string U_SBO_AGENCIA { get; set; }
        public double U_cuota_calculada { get; set; }
        public string U_HAB_AFILIACION { get; set; }
        public double U_monto_activar { get; set; }
        public string U_intercambio { get; set; }
        public string U_promotor_primera_afiliacion { get; set; }
        public string U_promotor_segunda_afiliacion { get; set; }
        public string U_promotor_tercera_afiliacion { get; set; }
        public string U_promotor_cuarta_afiliacion { get; set; }
        public string U_promotor_quinta_afiliacion { get; set; }
        public object U_motivo_baja { get; set; }
        public object U_tipo_sociedad { get; set; }
        public object U_estado_constitucion { get; set; }
        public object U_provincia_padron { get; set; }
        public object U_estado_poder { get; set; }
        public object U_ciudad_emision_poder { get; set; }
        public object U_nro_empleados { get; set; }
        public object U_nro_testimonio { get; set; }
        public object U_fecha_testimonio { get; set; }
        public object U_nro_testimonio_mod { get; set; }
        public object U_fecha_testimonio_mod { get; set; }
        public object U_nro_poder { get; set; }
        public object U_notaria_poder { get; set; }
        public object U_notaria_constitucion { get; set; }
        public object U_dj_poder { get; set; }
        public object U_dj_constitucion { get; set; }
        public object U_seccion { get; set; }
        public object U_actividad_principal { get; set; }
        public object U_actividad_secundaria { get; set; }
        public object U_ciu { get; set; }
        public object U_fecha_poder { get; set; }
        public double U_VALOR_AFILIACION { get; set; }
        public string U_CuotaManual { get; set; }
        public object U_MultiploAnterior { get; set; }
        public object U_MultiploBase { get; set; }
        public double U_CuotaAnterior { get; set; }
        public object U_nombrespn { get; set; }
        public object U_apellidospn { get; set; }
        public string U_nombre_facturacion { get; set; }
        public object U_correos_facturacion_elec { get; set; }
        public object U_Porcentaje_dui { get; set; }
        public string U_nit_facturacion { get; set; }
        public string U_formato_nit { get; set; }
        public object U_sector { get; set; }
        public object U_codigo_crm { get; set; }
        public List<object> BPAddresses { get; set; }
        public List<object> ContactEmployees { get; set; }
        public List<object> BPAccountReceivablePaybleCollection { get; set; }
        public List<object> BPPaymentMethods { get; set; }
        public List<BPWithholdingTaxCollection> BPWithholdingTaxCollection { get; set; }
        public List<object> BPPaymentDates { get; set; }
        public List<object> BPBranchAssignment { get; set; }
        public List<object> BPBankAccounts { get; set; }
        public List<object> BPFiscalTaxIDCollection { get; set; }
        public List<object> DiscountGroups { get; set; }
        public BPIntrastatExtension BPIntrastatExtension { get; set; }
        public List<object> BPBlockSendingMarketingContents { get; set; }
    }
}
